image:
  repository: docker.io/brandawg93/peanut
  tag: 5.11.0@sha256:c5b584fbb3bc55d30157353b53e6e972198cb83e648ab1911eb033882af35d82
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10688

persistence:
  config:
    enabled: true
    mountPath: "/config"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            WEB_PORT: "{{ .Values.service.main.ports.main.port }}"
