image:
  repository: docker.io/ayufan/proxmox-backup-server
  tag: v4.0.12@sha256:9c5a38316a935a45ce78fff12e6acf4770e20acc15fa59a01c36a836f63d88bf
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 8007
        protocol: https
        port: 8007

workload:
  main:
    podSpec:
      # It's used in the certificate generation
      # Without this it exceeds the 64 character limit
      # This limit comes from the crypt C library.
      hostname: pbs
      containers:
        main:
          probes:
            liveness:
              type: https
            readiness:
              type: https
            startup:
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /etc/proxmox-backup
  lib:
    enabled: true
    type: emptyDir
    mountPath: /var/lib/proxmox-backup
  log:
    enabled: true
    type: emptyDir
    mountPath: /var/log/proxmox-backup
  run:
    enabled: true
    type: emptyDir
    mountPath: /run
