image:
  repository: docker.io/linuxserver/transmission
  pullPolicy: IfNotPresent
  tag: 4.0.6@sha256:276f443d0c0f1d45ac3277ef56ff9b4d2b60a7a56059ec4dcf897f60692f6045
service:
  main:
    ports:
      main:
        port: 9091
        targetPort: 9091
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 51414
        protocol: tcp
      torrentudp:
        enabled: true
        port: "{{ .Values.service.torrent.ports.torrent.port }}"
        protocol: udp
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: tcp
            startup:
              enabled: true
              type: tcp
            readiness:
              enabled: true
              type: tcp
          env:
            PEERPORT: "{{ .Values.service.torrent.ports.torrent.port }}"
persistence:
  config:
    enabled: true
    mountPath: "/config"

manifestManager:
  enabled: false
