image:
  pullPolicy: IfNotPresent
  repository: docker.io/splunk/splunk
  tag: 9.4.4@sha256:3830c74a436d7cbf433f715cb6f711bcf7af2139cc2257fd5ba9aff0a6428cb0
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  dataingest:
    enabled: true
    ports:
      dataingest:
        enabled: true
        port: 9997
        protocol: http
        targetPort: 9997
  main:
    ports:
      main:
        port: 8000
        protocol: http
        targetPort: 8000
  hec:
    enabled: true
    ports:
      hec:
        enabled: true
        port: 8088
        protocol: http
        targetPort: 8088
  management:
    enabled: true
    ports:
      management:
        enabled: true
        port: 8089
        protocol: http
        targetPort: 8089
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SPLUNK_START_ARGS: --accept-license
            SPLUNK_PASSWORD: changeme
persistence:
  appcreds:
    enabled: true
    mountPath: /opt/splunk/etc/
  config:
    enabled: true
    mountPath: /opt/splunk/var
  data:
    enabled: true
    mountPath: /splunkdata
