image:
  repository: docker.io/rhasspy/wyoming-piper
  pullPolicy: IfNotPresent
  tag: 1.6.3@sha256:2f5de2c89bfb87e7b625265315a9d9f6deb5db44cec3a3e9aa0087d002eac459

service:
  main:
    ports:
      main:
        port: 10200
        protocol: tcp
        targetPort: 10200

wyoming_piper:
  voice: en_US-lessac-medium
  # custom_voice: ""
  speaker: 0
  length_scale: "1.0"
  noise_scale: "0.667"
  noise_w: "0.333"
  max_piper_procs: 1

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              port: 10200
              type: tcp
            readiness:
              port: 10200
              type: tcp
            startup:
              port: 10200
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /data
