image:
  repository: ghcr.io/linuxserver/boinc
  pullPolicy: IfNotPresent
  tag: latest@sha256:18c6838c9a342a6969fd9d8136d8dbf5d115636104a8b1246da4927cebf4b830
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 8080
        protocol: http
        port: 10142
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
