image:
  repository: ghcr.io/ajnart/homarr
  tag: 0.16.0@sha256:737ec361ed248b6d2b62b037da816f283b0484e0b94bc9876945c7c602e7307c
  pullPolicy: IfNotPresent
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NEXTAUTH_SECRET:
              secretKeyRef:
                name: homarr-secrets
                key: NEXTAUTH_SECRET
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  config:
    enabled: true
    mountPath: "/app/data/configs"
  icons:
    enabled: true
    mountPath: "/app/public/icons"
  data:
    enabled: true
    mountPath: "/data"
