image:
  repository: ghcr.io/linuxserver/grocy
  tag: 4.5.0@sha256:25cb87f21f99acfb50c28374898048f90b5abcebe14eec2cafcf53a5736aa651
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10013
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
