# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/dictionarry-hub/profilarr
  pullPolicy: IfNotPresent
  tag: 2.0.8@sha256:bcec9c579358163004145105c2747d3513ae75a56cd8b6c3ac759a0166d5b4af
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 6868
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            HOST: 0.0.0.0
            # Auth mode (on, oidc, off)
            # on is default
            AUTH: "on"
            # OIDC_CLIENT_ID: ""
            # OIDC_CLIENT_SECRET: ""
            # OIDC_DISCOVERY_URL: ""
            # auto set url
            ORIGIN: "{{ .Values.chartContext.appUrl }}"
persistence:
  config:
    enabled: true
    mountPath: "/config"
