image:
  pullPolicy: IfNotPresent
  repository: docker.io/sourcegraph/server
  tag: 6.6.2517@sha256:3fde5533eecf5c5fb46fdb2aecc0d12d52fc152ddb5e675bf764000b94ed64c8
persistence:
  applicationdatastoragepath:
    enabled: true
    mountPath: /var/opt/sourcegraph
  configstoragepath:
    enabled: true
    mountPath: /etc/sourcegraph

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  adminconsolepo:
    enabled: true
    ports:
      adminconsolepo:
        enabled: true
        port: 2633
        protocol: tcp
        targetPort: 2633
  grafanaport:
    enabled: true
    ports:
      grafanaport:
        enabled: true
        port: 3370
        protocol: tcp
        targetPort: 3370
  main:
    ports:
      main:
        port: 7080
        protocol: http
        targetPort: 7080
