image:
  repository: docker.io/vabene1111/recipes
  pullPolicy: IfNotPresent
  tag: 2.0.1@sha256:b95f7b3e3df000cd39a152be0ddff7139c6d7c5f59cd306f325da44c50a81d05
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_ENGINE: django.db.backends.postgresql
            POSTGRES_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            POSTGRES_PORT: 5432
            POSTGRES_USER: "{{ .Values.cnpg.main.user }}"
            POSTGRES_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            POSTGRES_DB: "{{ .Values.cnpg.main.database }}"
            TANDOOR_PORT: "{{ .Values.service.main.ports.main.port }}"
            ALLOWED_HOSTS: "*"
            COMMENT_PREF_DEFAULT: 1
            CSRF_TRUSTED_ORIGINS: ""
            DEBUG: 0
            FRACTION_PREF_DEFAULT: 0
            GUNICORN_MEDIA: 1
            SECRET_KEY:
              secretKeyRef:
                key: SECRET_KEY
                name: recipes-secrets
            SHOPPING_MIN_AUTOSYNC_INTERVAL: 5
            TIMEZONE: "{{ .Values.TZ }}"
service:
  main:
    ports:
      main:
        port: 10029
ingress:
  main:
    integrations:
      homepage:
        widget:
          type: tandoor
persistence:
  media:
    enabled: true
    mountPath: /opt/recipes/mediafiles
  static:
    enabled: true
    mountPath: /opt/recipes/staticfiles
    type: emptyDir
cnpg:
  main:
    enabled: true
    user: recipes
    database: recipes
