image:
  repository: twinproduction/gatus
  pullPolicy: IfNotPresent
  tag: v5.21.0@sha256:b45c89b1f8bfd5be456306b2bf1a581cc13ca0d897faf357ef77c35ac9eca1fa

service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080

persistence:
  config:
    enabled: true
    mountPath: /config/config.yaml
    subPath: config.yaml
    readOnly: true
    type: "configmap"
    objectName: config

configmap:
  config:
    enabled: true
    data:
      config.yaml: |
        {{- if .Values.cnpg.main.enabled }}
        storage:
          type: postgres
          path: {{ (printf "%s?client_encoding=utf8" (.Values.cnpg.main.creds.std | trimAll "\"")) | quote }}
        {{- end }}

        endpoints:
          - name: example
            url: https://example.org
            interval: 60s
            conditions:
              - "[STATUS] == 200"
              - "[BODY] == pat(*<h1>Example Domain</h1>*)"

cnpg:
  main:
    enabled: true
    user: gatus
    database: gatus
