image:
  repository: ghcr.io/linuxserver/projectsend
  pullPolicy: IfNotPresent
  tag: latest@sha256:1a4910e5071e852fc1397b173cdcd6ead93d9f3cefe72f4f34e2b1cddb30cd92
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 80
        port: 10127
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MAX_UPLOAD: 5000
            PHP_MEMORY_LIMIT: "512M"
            PHP_MAX_FILE_UPLOAD: 200
persistence:
  config:
    enabled: true
    mountPath: "/config"
  projectsend-config:
    enabled: true
    type: configmap
    objectName: projectsend-config
    mountPath: /config/projectsend/sys.config.php
    subPath: sys.config.php
    readOnly: true
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: true
mariadb:
  enabled: true
  mariadbUsername: projectsend
  mariadbDatabase: projectsend
