image:
  repository: docker.io/ghostfolio/ghostfolio
  pullPolicy: IfNotPresent
  tag: 2.189.0@sha256:2e8f834e24fe98e84bf8eecb05b99611d201cbe0f7e240ac8656d6e01f5e5302
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 3333
        targetPort: 3333
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
              type: http
            readiness:
              path: "/"
              type: http
            startup:
              type: tcp
          env:
            ALPHA_VANTAGE_API_KEY: ""
            ACCESS_TOKEN_SALT:
              secretKeyRef:
                name: ghostfolio-secrets
                key: ACCESS_TOKEN_SALT
            JWT_SECRET_KEY:
              secretKeyRef:
                name: ghostfolio-secrets
                key: JWT_SECRET_KEY
            DATABASE_URL:
              secretKeyRef:
                name: ghostfolio-secrets
                key: DATABASE_URL
            REDIS_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "rediscreds" }}'
                key: plainhost
            REDIS_PASSWORD: "{{ .Values.redis.password }}"
            REDIS_PORT: "6379"
cnpg:
  main:
    enabled: true
    user: ghostfolio
    database: ghostfolio
redis:
  enabled: true
