image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0@sha256:6e80f1cb1aa4f10d322e9e2a4fdf4684426b28273e52f0a3629b8eb7b8ab7d50
  pullPolicy: Always
j21Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0-java21@sha256:6e80f1cb1aa4f10d322e9e2a4fdf4684426b28273e52f0a3629b8eb7b8ab7d50
  pullPolicy: Always
j21graalvmImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0-java21-graalvm@sha256:f0f0956c6ec675ff4174fa2717aabedfbd7b2a87a30020216f92cf25e1677057
  pullPolicy: Always
j21alpineImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0-java21-alpine@sha256:333672a4c275f5edbdc95fde83b928df262007fcb95c9319ce23001d05bf348c
  pullPolicy: Always
j17Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0-java17@sha256:a84f83e195d206cb3f3c5d6440fbd7c81f060e94b3615c64d00e717a7fcb689d
  pullPolicy: Always
j17jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2024.6.1-java17-jdk@sha256:2c43fcede436aff9f50b1adf4448d55d221651be471ef41412232c141bfa89f6
  pullPolicy: Always
j17graalvmImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0-java17-graalvm@sha256:7e10bc23c863c3fee38e6e1a9942072d2b67c3ba442c753a59437b5e519dca1d
  pullPolicy: Always
j17alpineImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0-java17-alpine@sha256:19d4ebe151b7835e707a871aec4da78cddb56c06b241ed7ad295620860504103
  pullPolicy: Always
j11Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0-java11@sha256:b3e6a861e6b61ab7df77a422fdbc54a8df37e8b7c8e1670cc2da3b4b5d21205b
  pullPolicy: Always
j8Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0-java8@sha256:dc66fb95ee34448b149f258cabb6cb0eab1077b6773ed75a85bdebaf90999f76
  pullPolicy: Always
j8graalvmImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0-java8-graalvm-ce@sha256:84d4f98c55b5cad93692d2d43fedad0a69b7f79724e6bc56e89ba22677038042
  pullPolicy: Always
j8jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2025.8.0-java8-jdk@sha256:ed60d27d1f344fbce15ce44dd3834bccc12ef29ef1cf38844353987e87a2f85a
  pullPolicy: Always
j8alpineImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2024.9.0-java8-alpine@sha256:ee8505b9670a82b7703ec35b2a87fe9b7f7823b50ae50fad18bf1fe511e577f9
  pullPolicy: Always
mcBackupImage:
  repository: docker.io/itzg/mc-backup
  tag: latest@sha256:ca16bbeca04ce38469d187d9795985bf7e986d4798e330eb225e8cb9c1fba199
  pullPolicy: Always

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        protocol: tcp
        port: 25565
      query:
        enabled: true
        protocol: udp
        port: 25565
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25575

mcbackup:
  zstd_params:
    - --long=25
    - --single-thread
  # comma separated list
  excludes:
    - "*.jar"
    - "cache"
    - "logs"
    - "*.tmp"

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - mc-health
            readiness:
              enabled: true
              type: exec
              command:
                - mc-health
            startup:
              enabled: true
              type: exec
              command:
                - mc-health
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            ENABLE_QUERY: "true"
            EULA: "TRUE"
            GUI: "FALSE"
            OVERRIDE_SERVER_PROPERTIES: true
            VERSION: "LATEST"
            TYPE: "VANILLA"
            DIFFICULTY: easy
            MAX_PLAYERS: 20
            MAX_WORLD_SIZE: 10000
            ALLOW_NETHER: true
            ANNOUNCE_PLAYER_ACHIEVEMENTS: true
            ENABLE_COMMAND_BLOCK: false
            FORCE_GAMEMODE: false
            GENERATE_STRUCTURES: true
            HARDCORE: false
            MAX_BUILD_HEIGHT: 256
            MAX_TICK_TIME: 60000
            SPAWN_ANIMALS: true
            SPAWN_MONSTERS: true
            SPAWN_NPCS: true
            VIEW_DISTANCE: 16
            MODE: survival
            MOTD: "Welcome to Minecraft on TrueNAS Scale!"
            PVP: false
            LEVEL_TYPE: DEFAULT
            LEVEL: world
            ONLINE_MODE: true
            MEMORY: 2048M
            RCON_PASSWORD: "secretrconpass"
            # PACKWIZ_URL: ""
            # CUSTOM_SERVER: ""
            # QUILT_LOADER_VERSION: ""
            # QUILT_LAUNCHER: ""
            # QUILT_LAUNCHER_URL: ""
            # PUFFERFISH_BUILD: "lastSuccessfulBuild"
            # FORGEVERSION: ""
            # FORGE_INSTALLER: ""
            # FORGE_INSTALLER_URL: ""
            # FABRIC_LOADER_VERSION: ""
            # FABRIC_INSTALLER: ""
            # FABRIC_INSTALLER_URL: ""
            # SPIGOT_DOWNLOAD_URL: ""
            # BUILD_FROM_SOURCE: false
            # BUKKIT_DOWNLOAD_URL: ""
            # PAPERBUILD: ""
            # PAPER_DOWNLOAD_URL: ""
            # AIRPLANE_BUILD: "lastSuccessfulBuild"
            # MAGMA_CHANNEL: "stable"
            # MOHIST_BUILD: ""
            # CANYON_BUILD: ""
            # SPONGEBRANCH: "STABLE"
            # SPONGEVERSION: ""
            # LIMBO_BUILD: "LATEST"
            # LIMBO_SCHEMA_FILENAME: "default.schem"
            # CRUCIBLE_RELEASE: "latest"
            # FTB_MODPACK_ID: ""
            # FTB_MODPACK_VERSION_ID: ""
            # CF_SERVER_MOD: ""
            # CF_BASE_DIR: ""
            # USE_MODPACK_START_SCRIPT: true
            # FTB_LEGACYJAVAFIXER: false
            # WHITELIST: ""
            # OPS: ""
            # ICON: ""
            # SEED: ""
            # GENERATOR_SETTINGS: ""
            # WORLD: ""
            # FORCE_REDOWNLOAD: false
            # USE_FLARE_FLAGS: false
            # USE_AIKAR_FLAGS: true
            # USE_SIMD_FLAGS: false
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # CF_API_KEY
            # CF_PAGE_URL
            # CF_SLUG
            # CF_EXCLUDE_INCLUDE_FILE
            # CF_EXCLUDE_MODS
            # CF_FORCE_INCLUDE_MODS
            # CF_FORCE_SYNCHRONIZE
            # CF_OVERRIDES_SKIP_EXISTING
            # CF_PARALLEL_DOWNLOADS
            # CF_SET_LEVEL_FROM
        mcbackup:
          enabled: true
          imageSelector: mcBackupImage
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            BACKUP_METHOD: "tar"
            DEST_DIR: "{{.Values.persistence.backups.mountPath }}"
            SRC_DIR: "{{.Values.persistence.data.mountPath }}"
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            RCON_HOST: '{{ printf "%s-rcon" (include "tc.v1.common.lib.chart.names.fullname" $) }}'
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            RCON_PASSWORD: "{{ .Values.workload.main.podSpec.containers.main.env.RCON_PASSWORD }}"
            SERVER_HOST: '{{ include "tc.v1.common.lib.chart.names.fullname" $ }}'

            ZSTD_PARAMETERS: '{{ join " " .Values.mcbackup.zstd_params }}'
            EXCLUDES: '{{ join "," .Values.mcbackup.excludes }}'

            INITIAL_DELAY: "2m"
            BACKUP_INTERVAL: "24h"
            PRUNE_BACKUPS_DAYS: "7"
            PAUSE_IF_NO_PLAYERS: "false"
            PLAYERS_ONLINE_CHECK_INTERVAL: "5m"
            LINK_LATEST: "false"
            TAR_COMPRESS_METHOD: "zstd"

persistence:
  data:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /data
        mcbackup:
          mountPath: /data
          readOnly: true
  backups:
    enabled: true
    targetSelector:
      main:
        mcbackup:
          mountPath: /backups
