image:
  repository: docker.io/shlinkio/shlink-web-client
  pullPolicy: IfNotPresent
  tag: 4.5.0@sha256:d62fd301de3b798bfea094e3043886f5cf529c10c4b12d77b5f961a61987d357
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10154
        protocol: http

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SHLINK_SERVER_URL: ""
            SHLINK_SERVER_API_KEY: ""
            SHLINK_SERVER_NAME: ""
