image:
  repository: public.ecr.aws/docker/library/xwiki
  tag: 17.6.0-postgres-tomcat@sha256:6cc252d9adaf9040d5089d9cf89d05ad12d7fe6aff183ac88c136c043baafcc0
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10208
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/usr/local/xwiki"
cnpg:
  main:
    enabled: true
    user: xwiki
    database: xwiki

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_USER: "{{ .Values.cnpg.main.user }}"
            DB_DATABASE: "{{ .Values.cnpg.main.database }}"
            # User Defined
            JAVA_OPTS: ""
            DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            DB_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
