image:
  repository: ghcr.io/linuxserver/smokeping
  pullPolicy: IfNotPresent
  tag: 2.9.0@sha256:2b331d68e18d915b5e3ae6bc4bf5a123d749cb08ee809832c3b9ef7cc922fd7b
strategy:
  type: Recreate
service:
  main:
    ports:
      main:
        port: 10030
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: false

securityContext:
  container:
    capabilities:
      add:
        - NET_RAW
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
