image:
  repository: ghcr.io/linuxserver/bookstack
  pullPolicy: IfNotPresent
  tag: 25.07.20250804@sha256:4c6b0f491dc6ffe6ed00bdcc734c24883d8bdd1c3ca4497f516c2a5ad2eb9360
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10112
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_USERNAME: "{{ .Values.mariadb.mariadbUsername }}"
            DB_DATABASE: "{{ .Values.mariadb.mariadbDatabase }}"
            APP_URL: ""
            DB_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            DB_PASSWORD: "{{ .Values.mariadb.password }}"
            APP_KEY:
              secretKeyRef:
                name: secrets
                key: APP_KEY
persistence:
  config:
    enabled: true
    mountPath: /config
mariadb:
  enabled: true
  mariadbUsername: bookstack
  mariadbDatabase: bookstack
