image:
  repository: quay.io/jupyter/base-notebook
  pullPolicy: IfNotPresent
  tag: 2025-08-04@sha256:811daea9eff77cf57835e40ceb55d31e4b35989b27f84e84ef8f28dff33219f5
minimalImage:
  repository: quay.io/jupyter/minimal-notebook
  pullPolicy: IfNotPresent
  tag: 2025-08-04@sha256:2f2e13feaf2da772af15125659916eaf6d518a16878d9861aa911f029100c184
rImage:
  repository: quay.io/jupyter/r-notebook
  pullPolicy: IfNotPresent
  tag: 2025-08-04@sha256:8d0676a06d3d728b2f7164fe51487373edf1a8e3f743113437dde6f2644d0be4
scipyImage:
  repository: quay.io/jupyter/scipy-notebook
  pullPolicy: IfNotPresent
  tag: 2025-08-04@sha256:104390c7d0aa3988bab2ed2c38fcdd456427bbc67182a0d18bc045511d37c589
tensorflowImage:
  repository: quay.io/jupyter/tensorflow-notebook
  pullPolicy: IfNotPresent
  tag: 2025-08-04@sha256:5c1a2bcebc6d4ec642323cc615cffb37b6fca64944ed45d0c4175b914ecf2444
datascienceImage:
  repository: quay.io/jupyter/datascience-notebook
  pullPolicy: IfNotPresent
  tag: 2025-08-04@sha256:e862beda57a1133da9f0fb445d017a4bccd7944621127b507973a6a47ac3b739
pysparkImage:
  repository: quay.io/jupyter/pyspark-notebook
  pullPolicy: IfNotPresent
  tag: 2025-08-04@sha256:98e40de2295cd315ffebd42b3f02fd77ef18996e98e6dc035d26f4a3464f8abb
allsparkImage:
  repository: quay.io/jupyter/all-spark-notebook
  pullPolicy: IfNotPresent
  tag: 2025-08-04@sha256:c360f75bbd75033eea3155f8f08e30d74f3074d200ae28308d1461a62662194c
jupyter:
  jupyter_cmd: lab
  restartable: true
service:
  main:
    ports:
      main:
        port: 10300
        protocol: http
        targetPort: 8888
persistence:
  data:
    enabled: true
    mountPath: /home/jovyan/work

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            NB_UID: "{{ .Values.securityContext.container.PUID }}"
            NB_GID: "{{ .Values.securityContext.pod.fsGroup }}"
            NB_UMASK: "{{ .Values.securityContext.container.UMASK }}"
            # User Defined
            DOCKER_STACKS_JUPYTER_CMD: "{{ .Values.jupyter.jupyter_cmd }}"
            RESTARTABLE: '{{ ternary "yes" "no" .Values.jupyter.restartable }}'
updated: true
