image:
  pullPolicy: IfNotPresent
  repository: docker.io/knex666/prpdf
  tag: latest@sha256:5ac34b051c991242577be5a11eea72c3d60a10e06ddaee31d214367843ec6ae0
persistence:
  config:
    enabled: true
    mountPath: /source/config
  files:
    enabled: true
    mountPath: /Archiv/
  hostpath2:
    enabled: true
    mountPath: /source/static/pdf/

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
