image:
  pullPolicy: IfNotPresent
  repository: docker.io/yacy/yacy_search_server
  tag: latest@sha256:61b4c888bb5ecb3ccd0b045ccd6dd2510df38b891bbc6fbbdeb0e3adba7a1034
persistence:
  appdata:
    enabled: true
    mountPath: /opt/yacy_search_server/DATA

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  https:
    enabled: true
    ports:
      https:
        enabled: true
        port: 8443
        protocol: tcp
        targetPort: 8443
  main:
    ports:
      main:
        port: 8090
        protocol: http
        targetPort: 8090
