image:
  repository: monica
  tag: 4.1.2@sha256:797a3499eadd5f27e0ba6692b4e5f4861017e510c4cf21579b589c2f7cf92440
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10119
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/var/www/html/storage"
mariadb:
  enabled: true
  mariadbUsername: monica
  mariadbDatabase: monica

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            APP_ENV: production
            APP_URL: https://crm.k8s-at-home.com
            DB_DATABASE: monica
            DB_USERNAME: monica
            DB_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            DB_PASSWORD: "{{ .Values.mariadb.password }}"
            APP_KEY:
              secretKeyRef:
                name: appkey
                key: appkey
